language: python
Python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python setup.py test
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "Your encrypted token"
  on:
    tags: true
    branch: main
